### ISSUE TITLE
Missing ARM platform docker images

### ISSUE THREAD

**Issue by karlomikus** [alexbates/Tamari#2]
I want to run Tamari on raspberry pi 5 but seems there are no docker images targeting ARM platform available.

```
! tamari The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by alexbates** [comment]
There are now two docker images for v0.6, arm64 and amd64. Pulling alexbates/tamari:0.6 will select the correct architecture. I just tested on a Raspberry Pi 4 1GB and it seems to be working well. Let me know if any issues :)

**Comment by karlomikus** [comment]
Thanks, I've got it running!
