### ISSUE TITLE
Feature Request : Locking new registrations

### ISSUE THREAD

**Issue by IlanKD** [alexbates/Tamari#6]
Hi again,

It would be cool if we could lock new registrations in order to keep the website for private use.

Thanks for your cool tool ! It's really pretty too.

**Comment by alexbates** [comment]
Good idea and thanks for suggesting! I implemented this today. You can now disable registrations in config.py, or if using Docker can add "-e REG_DISABLED=True" to the "docker run" command. Pushed new v0.9 Docker images to support this. I will close this issue.
